name: Read Telegram Channel

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install telethon
          pip install requests
          pip install google-genai
          pip install pillow

      - name: Read channel
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          TELEGRAM_SESSION: ${{ secrets.TELEGRAM_SESSION }}
          
        run: python read_channel.py

      - name: Gemini Test
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python gemini_test.py
      - name: Create Collage
        run: python create_collage.py
      - name: Upload Images
        uses: actions/upload-artifact@v4
        with:
          name: product-images
          path: downloads/
      - name: Upload Marketing Package
        uses: actions/upload-artifact@v4
        with:
          name: marketing-package
          path: |
                product.json
                product_summary.json
                price_db.json

                ai_result.json
                marketing_package.json

                facebook_post_soft.txt
                facebook_post_sales.txt
                facebook_post_viral.txt
                facebook_post_short.txt

                story_post.txt
                reel_idea.txt

                selling_points.json
                customer_questions.json
                carousel_order.json

                cover_image.jpg
                marketing_collage.jpg

                selected_images/
